name: Sync Fork with Upstream (EcoWatt)

on:
  schedule:
    - cron: '0 3 * * *'  # Every day at 3 AM UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/Abithan07/EcoWatt-Device.git || true
          git fetch upstream

      - name: Merge upstream changes
        run: |
          if git show-ref --quiet refs/remotes/upstream/main; then
            BRANCH=main
          elif git show-ref --quiet refs/remotes/upstream/master; then
            BRANCH=master
          else
            echo "No main or master branch found in upstream"
            exit 0
          fi
          git checkout $BRANCH
          git merge upstream/$BRANCH || true

      - name: Push changes to your fork
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push origin $BRANCH
